name:  CI/CD

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      -  master

  pull_request:
    branches:
      - master

jobs:
  primary:
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.19.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.19.0
      - name: set environment
        run: export NODE_OPTIONS=--openssl-legacy-provider
      - name: install dependencies
        run: npm install
      - name: test env
        run: echo $NODE_OPTIONS
      - name: build
        run: npm run build
      - name: generate static pages
        run: npm run scully

      # should save this keys in github, settings of the project, secrets :
      # AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
      - name: aws deploy on scriptchess.com
        run: BUILD_DIRECTORY=dist/static BUCKET_NAME=scriptchess.com AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} npm run deploy-aws
      - name: invalidate cloudfront
        run: DISTRIBUTION_ID=E1VV4H17VBT521 AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} npm run invalidate-cloudfront
